// Auto-generated TypeScript definitions for lucide-react
// Generated by scripts/generate-lucide-types.mjs
import * as React from 'react';

export interface LucideProps extends React.SVGProps<SVGSVGElement> {
  size?: number | string;
  color?: string;
}


