# ============================
# Workers Dockerfile
# ============================
FROM analytics-core-base:latest

# ============================
# Répertoire de travail
# ============================
WORKDIR /app


CMD ["python", "-u", "workers/wsgi.py"]