FROM analytics-core-base:latest

WORKDIR /app/ai

EXPOSE 5001

# CMD pour Gunicorn
CMD ["gunicorn","wsgi:app","--bind", "0.0.0.0:5001","--workers", "2","--worker-class", "gthread","--threads", "8","--timeout", "300","--access-logfile", "-", "--error-logfile", "-"]
